version: "3.1"

services:
  rng:
    image: user/dc_rng:1.0
    networks:
    - nat
    ports:
    - "8001:80"

  hasher:
    image: user/dc_hasher:1.0
    networks:
    - nat
    ports:
    - "8002:80"

  webui:
    image: user/dc_webui:1.0
    networks:
    - nat
    ports:
    - "8000:80"

  redis:
    image: redis:3.2-nanoserver
    networks:
    - nat

  worker:
    image: user/dc_worker:1.0
    networks:
    - nat

networks:
  nat:
    external: true
