version: "3.1"

services:
  rng:
    image: user/windows_rng:1.0
    networks:
    - nat
    ports:
    - "8001:80"

  hasher:
    image: user/windows_hasher:1.0
    networks:
    - nat
    ports:
    - "8002:80"

  webui:
    image: user/windows_webui:1.0
    networks:
    - nat
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - nat

  worker:
    image: user/windows_worker:1.0
    networks:
    - nat

networks:
  nat:
    external: true
